SCALRCORE-10952 Fix Celery testsuite for Windows
Scalr/celery pull request #11
Opened 2019-01-31 16:57 UTC by danikmil

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Please describe your pull request.

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

2019-01-31 17:43 UTC, maratkomarov requested changes

2019-01-31 17:43 UTC, maratkomarov commented on t/unit/worker/test_strategy.py
> +            # skip this as no needed (see SCALRCORE-8536 (FAM-328))
@danikmil мы после вернули events, и сейчас у worker  они включены https://github.com/Scalr/fatmouse/blob/412f9abd756073bb2b006ba880e3feeef9c3c4b6/server/config.py#L86 Тесты падают правильно, у нас что что-то не работает.

2019-01-31 17:43 UTC, maratkomarov commented on t/unit/worker/test_strategy.py
> +            # assert not C.event_sent()
@danikmil тоже

2019-01-31 17:47 UTC, danikmil commented on t/unit/worker/test_strategy.py
> +            # skip this as no needed (see SCALRCORE-8536 (FAM-328))
@maratkomarov Ок, тоді нам потрібно ревертнути цей код https://github.com/Scalr/celery/pull/10/files#diff-597c6d19a19514040fc98bf8473ded58R116 так як він дебрікейтить фічу

2019-02-01 13:43 UTC, danikmil commented on t/unit/worker/test_strategy.py
> +            # skip this as no needed (see SCALRCORE-8536 (FAM-328))
@maratkomarov Вернув назад код з events, пофіксив юніттест, все завелось. Збілдив нові імеджи на основі даного коду, поки проблем не бачу, все працює.

2019-02-21 16:35 UTC, maratkomarov approved these changes

2019-02-21 16:35 UTC, merged