SCALRCORE-11936 Celery: task.get() does not return result (ex. Monitor: Expand info in the log)
Scalr/celery pull request #15
Opened 2019-03-20 17:05 UTC by sk1project

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

The changes fix RPC backend consumer reviving after reconnection to RabbitMQ 

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

2019-03-25 20:59 UTC, maratkomarov requested changes

2019-03-25 20:59 UTC, maratkomarov commented on celery/worker/consumer/consumer.py
> +                    # SCALRCORE-11936 Callback to revive RPC backend consumer
@sk1project по логике слоев revive следует сделать до делегирования логики blueprint.restart(self)-у. Тк там в теории уже могут быть какие-то завязки на работающие коннкшны.

2019-03-25 22:57 UTC, sk1project commented on celery/worker/consumer/consumer.py
> +                    # SCALRCORE-11936 Callback to revive RPC backend consumer
@maratkomarov Нет, нам нужен уже установленный коннекшин, который мы берем из app. Бакэнд не менеджит коннекшин и канал, это делает blueprint.

2019-03-26 00:06 UTC, maratkomarov approved these changes

2019-03-27 22:48 UTC, merged